In [1]:
print("jfb")

jfb

In [ ]:
def func(L) :
    for i in L:
        if i == 0:
            L.remove(i)
            L.append(0)

    return L

In [41]:
L = [0]

In [42]:
func(L)

[0]

In [49]:
def remove_extra_spaces(text):
    print(text.split())
    return " ".join(text.split())

# Example usage:
dirty_text = "   Hello    beautiful     World!   "
clean_text = remove_extra_spaces(dirty_text)
print(repr(clean_text))  # Output: 'Hello beautiful World!'

['Hello', 'beautiful', 'World!']
'Hello beautiful World!'

In [50]:
text = "python is FUN! and powerful."
result = text.capitalize()

print(result)

Python is fun! and powerful.

In [51]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmed", None, "Sara", "Usman"],
    "Age": [21, "22", 23, None, "twenty-four"],
    "Salary": [50000, "60000", None, 75000, "N/A"],
    "City": ["Lahore", "Karachi", None, 123, "Islamabad"],
    "Email": ["ali@gmail.com", None, "sara@gmail.com", "N/A", "usman@gmail.com"]
}

df = pd.DataFrame(data)

print(df)

    Name          Age Salary       City            Email
0    Ali           21  50000     Lahore    ali@gmail.com
1  Ahmed           22  60000    Karachi              NaN
2    NaN           23   None       None   sara@gmail.com
3   Sara         None  75000        123              N/A
4  Usman  twenty-four    N/A  Islamabad  usman@gmail.com

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      object
 2   Salary  4 non-null      object
 3   City    4 non-null      object
 4   Email   4 non-null      str
dtypes: object(3), str(2)
memory usage: 396.0+ bytes

In [53]:
df.isna().sum()

Name      1
Age       1
Salary    1
City      1
Email     1
dtype: int64

In [2]:
import pandas as pd

data = {
    "Employee": [
        "Ali", "Ahmed", "Sara", "Usman", "Ali",
        "Ahmed", "Sara", "Usman", "Ali", "Ahmed",
        "Sara", "Usman", "Ali", "Ahmed", "Sara"
    ],
    
    "Department": [
        "IT", "Sales", "HR", "IT", "Sales",
        "HR", "IT", "Sales", "HR", "IT",
        "Sales", "HR", "IT", "Sales", "HR"
    ],
    
    "City": [
        "Lahore", "Karachi", "Lahore", "Islamabad", "Karachi",
        "Islamabad", "Lahore", "Karachi", "Islamabad", "Lahore",
        "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad"
    ],
    
    "Product": [
        "Laptop", "Mobile", "Tablet", "Laptop", "Mobile",
        "Tablet", "Laptop", "Mobile", "Tablet", "Laptop",
        "Mobile", "Tablet", "Laptop", "Mobile", "Tablet"
    ],
    
    "Quantity": [
        5, 8, 6, 4, 10,
        7, 3, 12, 9, 6,
        15, 8, 7, 11, 10
    ],
    
    "Sales": [
        500000, 320000, 180000, 400000, 400000,
        210000, 300000, 480000, 270000, 600000,
        600000, 240000, 700000, 440000, 300000
    ]
}

df = pd.DataFrame(data)

print(df)

   Employee Department       City Product  Quantity   Sales
0       Ali         IT     Lahore  Laptop         5  500000
1     Ahmed      Sales    Karachi  Mobile         8  320000
2      Sara         HR     Lahore  Tablet         6  180000
3     Usman         IT  Islamabad  Laptop         4  400000
4       Ali      Sales    Karachi  Mobile        10  400000
5     Ahmed         HR  Islamabad  Tablet         7  210000
6      Sara         IT     Lahore  Laptop         3  300000
7     Usman      Sales    Karachi  Mobile        12  480000
8       Ali         HR  Islamabad  Tablet         9  270000
9     Ahmed         IT     Lahore  Laptop         6  600000
10     Sara      Sales    Karachi  Mobile        15  600000
11    Usman         HR  Islamabad  Tablet         8  240000
12      Ali         IT     Lahore  Laptop         7  700000
13    Ahmed      Sales    Karachi  Mobile        11  440000
14     Sara         HR  Islamabad  Tablet        10  300000

In [ ]:
df.groupby("Department")["Quantity"].mean()

Department
HR        8.0
IT        5.0
Sales    11.2
Name: Quantity, dtype: float64

In [9]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115],

    "Age": [20, 21, 20, 22, 21, 23, 20, 22, 21, 24,
            23, 20, 22, 21, 23],

    "Study_Hours": [4, 6, 3, 8, 5, 7, 2, 9, 6, 4,
                    8, 3, 7, 5, 9],

    "Attendance": [85, 90, 78, 95, 88, 92, 75, 96, 89, 82,
                   94, 80, 91, 87, 97],

    "Assignments": [7, 9, 6, 10, 8, 9, 5, 10, 8, 7,
                    9, 6, 10, 8, 10],

    "Midterm": [72, 85, 68, 91, 79, 88, 61, 94, 83, 70,
                89, 65, 92, 77, 95],

    "Final": [78, 88, 72, 94, 82, 91, 65, 96, 86, 75,
              93, 70, 95, 81, 97]
}

df = pd.DataFrame(data)

print(df)

    Student_ID  Age  Study_Hours  Attendance  Assignments  Midterm  Final
0          101   20            4          85            7       72     78
1          102   21            6          90            9       85     88
2          103   20            3          78            6       68     72
3          104   22            8          95           10       91     94
4          105   21            5          88            8       79     82
5          106   23            7          92            9       88     91
6          107   20            2          75            5       61     65
7          108   22            9          96           10       94     96
8          109   21            6          89            8       83     86
9          110   24            4          82            7       70     75
10         111   23            8          94            9       89     93
11         112   20            3          80            6       65     70
12         113   22            7          91           10       92     95
13         114   21            5          87            8       77     81
14         115   23            9          97           10       95     97

In [10]:
df.groupby("Final")["Age"].mean()

Final
65    20.0
70    20.0
72    20.0
75    24.0
78    20.0
81    21.0
82    21.0
86    21.0
88    21.0
91    23.0
93    23.0
94    22.0
95    22.0
96    22.0
97    23.0
Name: Age, dtype: float64

In [14]:
df.groupby(["Final", "Midterm"])["Attendance"].mean()

Final  Midterm
65     61         75.0
70     65         80.0
72     68         78.0
75     70         82.0
78     72         85.0
81     77         87.0
82     79         88.0
86     83         89.0
88     85         90.0
91     88         92.0
93     89         94.0
94     91         95.0
95     92         91.0
96     94         96.0
97     95         97.0
Name: Attendance, dtype: float64

In [15]:
df.columns

Index(['Student_ID', 'Age', 'Study_Hours', 'Attendance', 'Assignments',
       'Midterm', 'Final'],
      dtype='str')

In [21]:
df.groupby("Attendance").agg(
    Study_Hours=("Study_Hours", "mean"),
    Midterm=("Midterm", "mean"),
    Final=("Final", "mean")
)

            Study_Hours  Midterm  Final
Attendance
75                  2.0     61.0   65.0
78                  3.0     68.0   72.0
80                  3.0     65.0   70.0
82                  4.0     70.0   75.0
85                  4.0     72.0   78.0
87                  5.0     77.0   81.0
88                  5.0     79.0   82.0
89                  6.0     83.0   86.0
90                  6.0     85.0   88.0
91                  7.0     92.0   95.0
92                  7.0     88.0   91.0
94                  8.0     89.0   93.0
95                  8.0     91.0   94.0
96                  9.0     94.0   96.0
97                  9.0     95.0   97.0

In [23]:
df["Final_mean"] = df.groupby("Attendance")["Final"].transform("mean")

In [25]:
df

,Student_ID,Age,Study_Hours,Attendance,Assignments,Midterm,Final,Final_mean
0,101,20,4,85,7,72,78,78.0
1,102,21,6,90,9,85,88,88.0
2,103,20,3,78,6,68,72,72.0
3,104,22,8,95,10,91,94,94.0
4,105,21,5,88,8,79,82,82.0
5,106,23,7,92,9,88,91,91.0
6,107,20,2,75,5,61,65,65.0
7,108,22,9,96,10,94,96,96.0
8,109,21,6,89,8,83,86,86.0
9,110,24,4,82,7,70,75,75.0
10,111,23,8,94,9,89,93,93.0
11,112,20,3,80,6,65,70,70.0
12,113,22,7,91,10,92,95,95.0
13,114,21,5,87,8,77,81,81.0
14,115,23,9,97,10,95,97,97.0

In [ ]:
# pivot
# melt