series and dataframe

In [2]:
import pandas as pd

In [6]:
ages = pd.Series([1, 2, 3, 4], name="age")
ages

0    1
1    2
2    3
3    4
Name: age, dtype: int64

In [11]:
students = pd.DataFrame({
    "name" : ["Ali", "Muzzamal"],
    "age" : [19, 21],
    "passed" : [True, False]
})

In [12]:
students

       name  age  passed
0       Ali   19    True
1  Muzzamal   21   False

In [13]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Usman", "Ayesha"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 78, 92, 70, 88]
}

In [14]:
df = pd.DataFrame(data)

In [15]:
df

     Name  Age  Marks
0     Ali   20     85
1   Ahmed   21     78
2    Sara   19     92
3   Usman   22     70
4  Ayesha   20     88

In [16]:
df.head()

     Name  Age  Marks
0     Ali   20     85
1   Ahmed   21     78
2    Sara   19     92
3   Usman   22     70
4  Ayesha   20     88

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 275.0 bytes

In [ ]:
df.describe(include='all')

       Name        Age     Marks
count     5   5.000000   5.00000
unique    5        NaN       NaN
top     Ali        NaN       NaN
freq      1        NaN       NaN
mean    NaN  20.400000  82.60000
std     NaN   1.140175   8.70632
min     NaN  19.000000  70.00000
25%     NaN  20.000000  78.00000
50%     NaN  20.000000  85.00000
75%     NaN  21.000000  88.00000
max     NaN  22.000000  92.00000

In [27]:
df = pd.read_csv("work/pandas/student_data.csv")
df

,student_id,first_name,last_name,gender,age,grade_level,subject,test_score,attendance_percentage,study_hours_per_week,extracurricular,city
0,1001,Ali,Khan,M,15,9,Math,78,92,6,Cricket,Lahore
1,1002,Sara,Ahmed,F,16,10,Science,85,95,8,Debate Club,Karachi
2,1003,Bilal,Hussain,M,14,8,English,66,80,4,NaN,Islamabad
3,1004,Ayesha,Raza,F,15,9,Math,91,98,10,Chess Club,Lahore
4,1005,Usman,Malik,M,17,11,Physics,73,85,5,Football,Faisalabad
5,1006,Fatima,Iqbal,F,16,10,Chemistry,88,90,7,Art Club,Multan
6,1007,Hamza,Sheikh,M,14,8,Science,59,70,3,NaN,Lahore
7,1008,Zainab,Tariq,F,17,11,Biology,94,97,9,Science Club,Karachi
8,1009,Omar,Farooq,M,15,9,English,70,88,4,Cricket,Peshawar
9,1010,Mehak,Younas,F,14,8,Math,82,93,6,Dance,Lahore
10,1011,Saad,Chaudhry,M,16,10,Physics,64,75,3,NaN,Rawalpindi
11,1012,Hira,Nawaz,F,15,9,Chemistry,89,96,8,Debate Club,Karachi
12,1013,Talha,Aslam,M,17,11,Science,77,84,5,Football,Sialkot
13,1014,Nida,Baig,F,16,10,Biology,92,99,9,Science Club,Lahore
14,1015,Waleed,Siddiqui,M,14,8,English,55,68,2,NaN,Karachi
15,1016,Amna,Qureshi,F,15,9,Math,68,82,4,Art Club,Multan
16,1017,Faisal,Anwar,M,17,11,Physics,80,91,7,Chess Club,Lahore
17,1018,Rabia,Hameed,F,16,10,Chemistry,73,86,6,Dance,Islamabad
18,1019,Danish,Riaz,M,15,9,Science,86,94,8,Cricket,Faisalabad
19,1020,Sana,Yousaf,F,14,8,English,61,77,3,NaN,Lahore

In [33]:
import numpy as np

In [34]:
np.dtype(df["test_score"])

dtype('int64')

In [36]:
new_df = df[["first_name", "last_name", "gender"]]

In [43]:
new_df

   first_name last_name gender
0         Ali      Khan      M
1        Sara     Ahmed      F
2       Bilal   Hussain      M
3      Ayesha      Raza      F
4       Usman     Malik      M
5      Fatima     Iqbal      F
6       Hamza    Sheikh      M
7      Zainab     Tariq      F
8        Omar    Farooq      M
9       Mehak    Younas      F
10       Saad  Chaudhry      M
11       Hira     Nawaz      F
12      Talha     Aslam      M
13       Nida      Baig      F
14     Waleed  Siddiqui      M
15       Amna   Qureshi      F
16     Faisal     Anwar      M
17      Rabia    Hameed      F
18     Danish      Riaz      M
19       Sana    Yousaf      F

In [48]:
indexed = new_df.set_index("first_name")

In [52]:
indexed

           last_name gender
first_name
Ali             Khan      M
Sara           Ahmed      F
Bilal        Hussain      M
Ayesha          Raza      F
Usman          Malik      M
Fatima         Iqbal      F
Hamza         Sheikh      M
Zainab         Tariq      F
Omar          Farooq      M
Mehak         Younas      F
Saad        Chaudhry      M
Hira           Nawaz      F
Talha          Aslam      M
Nida            Baig      F
Waleed      Siddiqui      M
Amna         Qureshi      F
Faisal         Anwar      M
Rabia         Hameed      F
Danish          Riaz      M
Sana          Yousaf      F

In [55]:
print(indexed.loc[["Ali", "Sara"], "gender"])

first_name
Ali     M
Sara    F
Name: gender, dtype: str

In [60]:
df.iloc[0:4, 0:3]

   student_id first_name last_name
0        1001        Ali      Khan
1        1002       Sara     Ahmed
2        1003      Bilal   Hussain
3        1004     Ayesha      Raza

In [62]:
df.head()

,student_id,first_name,last_name,gender,age,grade_level,subject,test_score,attendance_percentage,study_hours_per_week,extracurricular,city
0,1001,Ali,Khan,M,15,9,Math,78,92,6,Cricket,Lahore
1,1002,Sara,Ahmed,F,16,10,Science,85,95,8,Debate Club,Karachi
2,1003,Bilal,Hussain,M,14,8,English,66,80,4,NaN,Islamabad
3,1004,Ayesha,Raza,F,15,9,Math,91,98,10,Chess Club,Lahore
4,1005,Usman,Malik,M,17,11,Physics,73,85,5,Football,Faisalabad

In [76]:
df[(df["attendance_percentage"] > 75) & (df["gender"] == 'M')]

,student_id,first_name,last_name,gender,age,grade_level,subject,test_score,attendance_percentage,study_hours_per_week,extracurricular,city
0,1001,Ali,Khan,M,15,9,Math,78,92,6,Cricket,Lahore
2,1003,Bilal,Hussain,M,14,8,English,66,80,4,NaN,Islamabad
4,1005,Usman,Malik,M,17,11,Physics,73,85,5,Football,Faisalabad
8,1009,Omar,Farooq,M,15,9,English,70,88,4,Cricket,Peshawar
12,1013,Talha,Aslam,M,17,11,Science,77,84,5,Football,Sialkot
16,1017,Faisal,Anwar,M,17,11,Physics,80,91,7,Chess Club,Lahore
18,1019,Danish,Riaz,M,15,9,Science,86,94,8,Cricket,Faisalabad

In [82]:
df["test_percentage"] = df["test_score"] / 100

In [83]:
df["passed"] = df["test_score"] >= 50

In [85]:
df["future_doctor"] = df["subject"] == "Biology"

In [86]:
df

,student_id,first_name,last_name,gender,age,grade_level,subject,test_score,attendance_percentage,study_hours_per_week,extracurricular,city,test_percentage,passed,future_doctor
0,1001,Ali,Khan,M,15,9,Math,78,92,6,Cricket,Lahore,0.78,True,False
1,1002,Sara,Ahmed,F,16,10,Science,85,95,8,Debate Club,Karachi,0.85,True,False
2,1003,Bilal,Hussain,M,14,8,English,66,80,4,NaN,Islamabad,0.66,True,False
3,1004,Ayesha,Raza,F,15,9,Math,91,98,10,Chess Club,Lahore,0.91,True,False
4,1005,Usman,Malik,M,17,11,Physics,73,85,5,Football,Faisalabad,0.73,True,False
5,1006,Fatima,Iqbal,F,16,10,Chemistry,88,90,7,Art Club,Multan,0.88,True,False
6,1007,Hamza,Sheikh,M,14,8,Science,59,70,3,NaN,Lahore,0.59,True,False
7,1008,Zainab,Tariq,F,17,11,Biology,94,97,9,Science Club,Karachi,0.94,True,True
8,1009,Omar,Farooq,M,15,9,English,70,88,4,Cricket,Peshawar,0.70,True,False
9,1010,Mehak,Younas,F,14,8,Math,82,93,6,Dance,Lahore,0.82,True,False
10,1011,Saad,Chaudhry,M,16,10,Physics,64,75,3,NaN,Rawalpindi,0.64,True,False
11,1012,Hira,Nawaz,F,15,9,Chemistry,89,96,8,Debate Club,Karachi,0.89,True,False
12,1013,Talha,Aslam,M,17,11,Science,77,84,5,Football,Sialkot,0.77,True,False
13,1014,Nida,Baig,F,16,10,Biology,92,99,9,Science Club,Lahore,0.92,True,True
14,1015,Waleed,Siddiqui,M,14,8,English,55,68,2,NaN,Karachi,0.55,True,False
15,1016,Amna,Qureshi,F,15,9,Math,68,82,4,Art Club,Multan,0.68,True,False
16,1017,Faisal,Anwar,M,17,11,Physics,80,91,7,Chess Club,Lahore,0.80,True,False
17,1018,Rabia,Hameed,F,16,10,Chemistry,73,86,6,Dance,Islamabad,0.73,True,False
18,1019,Danish,Riaz,M,15,9,Science,86,94,8,Cricket,Faisalabad,0.86,True,False
19,1020,Sana,Yousaf,F,14,8,English,61,77,3,NaN,Lahore,0.61,True,False

In [87]:
df = pd.read_csv("work/pandas/student_data_messy.csv")

In [89]:
df.head()

,student_id,first_name,last_name,gender,age,grade_level,subject,test_score,attendance_percentage,study_hours_per_week,city
0,1001,Ali,Khan,M,15.0,9,Math,78.0,92.0,6.0,Lahore
1,1002,Sara,Ahmed,Female,16.0,10,science,85.0,95.0,8.0,Karachi
2,1003,Bilal,Hussain,male,14.0,8,English,NaN,80.0,4.0,Islamabad
3,1004,Ayesha,Raza,F,15.0,9,Math,91.0,98.0,10.0,Lahore
4,1005,Usman,Malik,M,17.0,11,Physics,73.0,NaN,5.0,Faisalabad

In [91]:
df.shape

(21, 11)

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             21 non-null     int64
 1   first_name             21 non-null     str
 2   last_name              21 non-null     str
 3   gender                 21 non-null     str
 4   age                    20 non-null     float64
 5   grade_level            21 non-null     int64
 6   subject                21 non-null     str
 7   test_score             19 non-null     float64
 8   attendance_percentage  20 non-null     float64
 9   study_hours_per_week   20 non-null     float64
 10  city                   21 non-null     str
dtypes: float64(4), int64(2), str(5)
memory usage: 2.5 KB

In [96]:
df.describe()

,student_id,age,grade_level,test_score,attendance_percentage,study_hours_per_week
count,21.000000,20.000000,21.000000,19.000000,20.000000,20.000000
mean,1010.476190,15.400000,8.476190,81.578947,87.400000,6.000000
std,5.767313,1.095445,4.154745,20.353312,9.338094,2.247806
min,1001.000000,14.000000,-9.000000,55.000000,68.000000,2.000000
25%,1006.000000,14.750000,8.000000,70.500000,81.500000,4.000000
50%,1010.000000,15.000000,9.000000,82.000000,90.500000,6.000000
75%,1015.000000,16.000000,10.000000,88.500000,94.250000,8.000000
max,1020.000000,17.000000,11.000000,150.000000,99.000000,10.000000

In [99]:
df.duplicated().sum()

np.int64(1)

In [102]:
df.drop_duplicates(inplace=True)

In [107]:
df.isnull().sum()

student_id               0
first_name               0
last_name                0
gender                   0
age                      1
grade_level              0
subject                  0
test_score               2
attendance_percentage    1
study_hours_per_week     1
city                     0
dtype: int64

In [109]:
df.dropna(axis=0, inplace=True)

In [110]:
df.isnull().sum()

student_id               0
first_name               0
last_name                0
gender                   0
age                      0
grade_level              0
subject                  0
test_score               0
attendance_percentage    0
study_hours_per_week     0
city                     0
dtype: int64

In [116]:
df["gender"] = df["gender"].replace(["Female", "female"], "F")

In [125]:
df = df.set_index("student_id")

In [ ]:
df.columns

Index(['first_name', 'last_name', 'gender', 'age', 'grade_level', 'subject',
       'test_score', 'attendance_percentage', 'study_hours_per_week', 'city'],
      dtype='str')