In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("employees.csv")
df

    Age  Salary  Output
0    59  114651   84.69
1    49   93335   61.77
2    35   40965   28.90
3    28   54538   39.96
4    41  100592   66.19
..  ...     ...     ...
95   54   64698   54.56
96   53  110623   71.96
97   43   52671   39.94
98   44   55184   42.56
99   57   72107   43.75

[100 rows x 3 columns]

In [8]:
df.head()

   Age  Salary  Output
0   59  114651   84.69
1   49   93335   61.77
2   35   40965   28.90
3   28   54538   39.96
4   41  100592   66.19

In [9]:
df.sample(5)

    Age  Salary  Output
97   43   52671   39.94
27   36  111734   67.20
54   49   51959   47.18
46   55   53776   54.75
42   40  105766   69.22

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 
model = LinearRegression()

X = df[["Age", "Salary"]]
Y = df["Output"]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)