In [196]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [197]:
import os

In [198]:
os.listdir("drive/MyDrive/data/House-Prediction_Dataset")

['data.csv', 'output.csv', 'data.dat']

In [199]:
path = "/content/drive/MyDrive/data/House-Prediction_Dataset/data.csv"

In [200]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [201]:
df = pd.read_csv(path)

In [202]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [203]:
df[df["price"] == 0]["price"].value_counts()

df = df[df["price"] > 0]

In [204]:
X = df.drop("price", axis=1)
Y = df["price"]

In [205]:
X.head()

,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [206]:
X["date"] = pd.to_datetime(df["date"])
# separate day, month, year
X["year"] = X["date"].dt.year
X["month"] = X["date"].dt.month
X["day"] = X["date"].dt.day

# drop date column
X.drop("date", axis=1, inplace=True)

In [207]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4551 entries, 0 to 4599
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bedrooms       4551 non-null   float64
 1   bathrooms      4551 non-null   float64
 2   sqft_living    4551 non-null   int64
 3   sqft_lot       4551 non-null   int64
 4   floors         4551 non-null   float64
 5   waterfront     4551 non-null   int64
 6   view           4551 non-null   int64
 7   condition      4551 non-null   int64
 8   sqft_above     4551 non-null   int64
 9   sqft_basement  4551 non-null   int64
 10  yr_built       4551 non-null   int64
 11  yr_renovated   4551 non-null   int64
 12  street         4551 non-null   object
 13  city           4551 non-null   object
 14  statezip       4551 non-null   object
 15  country        4551 non-null   object
 16  year           4551 non-null   int32
 17  month          4551 non-null   int32
 18  day            4551 non-null   int32
dtypes: float64(3), int32(3), int64(9), object(4)
memory usage: 657.8+ KB

In [208]:
X["street"].nunique()

# street as larget category and act as id
X.drop("street", axis=1, inplace=True)

In [209]:
X["statezip"].nunique()
X[["state", "zip"]] = X["statezip"].str.split(" ", n=1, expand=True)

In [210]:
X["state"].nunique()
# state has unit value so there is no need of it
X.drop(["state", "statezip"], inplace=True, axis=1)

In [211]:
X["zip"] = pd.to_numeric(X["zip"], errors="coerce").astype("int64")

In [212]:
X["country"].nunique()
# as counrty as unique value so its can be skipes
X.drop("country", inplace=True, axis=1)

In [213]:
X["total_sqft"] = X["sqft_basement"] + X["sqft_above"]
X.drop(["sqft_basement", "sqft_above"], inplace=True, axis=1)

In [214]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4551 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   bedrooms      4551 non-null   float64
 1   bathrooms     4551 non-null   float64
 2   sqft_living   4551 non-null   int64
 3   sqft_lot      4551 non-null   int64
 4   floors        4551 non-null   float64
 5   waterfront    4551 non-null   int64
 6   view          4551 non-null   int64
 7   condition     4551 non-null   int64
 8   yr_built      4551 non-null   int64
 9   yr_renovated  4551 non-null   int64
 10  city          4551 non-null   object
 11  year          4551 non-null   int32
 12  month         4551 non-null   int32
 13  day           4551 non-null   int32
 14  zip           4551 non-null   int64
 15  total_sqft    4551 non-null   int64
dtypes: float64(3), int32(3), int64(9), object(1)
memory usage: 551.1+ KB

In [215]:
X["city"].nunique()

44

In [216]:
X["year"].nunique()
X.drop("year", axis=1, inplace=True)

In [217]:
y_log = np.log1p(Y)

In [218]:
from sklearn.model_selection import train_test_split

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=42, test_size=0.2)

In [220]:
from sklearn.preprocessing import OneHotEncoder

In [221]:
ohe = OneHotEncoder(handle_unknown="ignore")

In [222]:
X_train_city = ohe.fit_transform(X_train[["city"]])
X_test_city = ohe.transform(X_test[["city"]])

In [223]:
X_train_city

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3640 stored elements and shape (3640, 42)>

In [224]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_num = X_train.drop("city", axis=1)
X_test_num = X_test.drop("city", axis=1)

X_train_scale = scaler.fit_transform(X_train_num)
X_test_scale = scaler.transform(X_test_num)

In [225]:
X_train_final = np.hstack((X_train_scale, X_train_city.toarray()))
X_test_final = np.hstack((X_test_scale, X_test_city.toarray()))

In [226]:
X_train_final

array([[ 0.68289676, -0.51996945, -0.81710783, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42138765,  0.13313227,  0.09297492, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42138765, -1.49962204, -0.98841753, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.42138765, -1.49962204, -1.04195181, ...,  0.        ,
         0.        ,  0.        ],
       [-1.52567206, -1.49962204, -1.29891635, ...,  0.        ,
         0.        ,  0.        ],
       [-1.52567206, -1.49962204, -0.6779187 , ...,  0.        ,
         0.        ,  0.        ]])

In [227]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train_final, y_train)
y_pred = model.predict(X_test_final)

In [228]:
from sklearn.metrics import r2_score, mean_squared_error

r2_score(y_test, y_pred)

0.6734332481700354

In [229]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=200, random_state=42)

rf.fit(X_train_final, y_train)

y_predic = rf.predict(X_test_final)

r2_score(y_test, y_predic)

0.45963845914290713