In [393]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [394]:
import os
path = os.listdir('drive/MyDrive/data/Movie-Recommendation-System')
movies_path = os.path.join("/content/drive/MyDrive/data/Movie-Recommendation-System", path[0])
credits_path = os.path.join("/content/drive/MyDrive/data/Movie-Recommendation-System", path[1])

movies_path, credits_path

('/content/drive/MyDrive/data/Movie-Recommendation-System/tmdb_5000_movies.csv',
 '/content/drive/MyDrive/data/Movie-Recommendation-System/tmdb_5000_credits.csv')

In [395]:
import pandas as pd
import numpy as np

In [396]:
movies = pd.read_csv(movies_path)
credits = pd.read_csv(credits_path)

In [397]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [398]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [399]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [400]:
# remove missing 
movies.isna().sum().max()

3091

In [401]:
# remove missing 
credits.isna().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [402]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [403]:
movies = movies[["id", "genres", "keywords", "overview", "title"]]
movies.head(3)

,id,genres,keywords,overview,title
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre

In [404]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [405]:
credits = credits[[ 'title', 'cast', 'crew']]

In [406]:
movies.isna().sum()

id          0
genres      0
keywords    0
overview    3
title       0
dtype: int64

In [407]:
# drop missing columns
movies.dropna(inplace=True)

In [408]:
df = pd.merge(movies, credits, on="title")
df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [409]:
df.isna().sum()

id          0
genres      0
keywords    0
overview    0
title       0
cast        0
crew        0
dtype: int64

In [410]:
df["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [411]:
import ast


def convert(obj):
    return ast.literal_eval(obj)

In [412]:
df["genres"] = df["genres"].apply(convert)
df["genres"][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [413]:
df['cast'] = df["cast"].apply(convert)
type(df["cast"][0])

list

In [414]:
df['keywords'] = df["keywords"].apply(convert)
type(df["keywords"][0])

list

In [415]:
df["crew"] = df["crew"].apply(convert)
type(df["crew"][0])

list

In [416]:
# helper function to fetch name
def fetch_name(obj):
    L = []
    for i in obj:
        L.append(i["name"])
    return L

In [417]:
df["genres"] = df["genres"].apply(fetch_name)

In [418]:
df["keywords"] = df["keywords"].apply(fetch_name)
df["keywords"]

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4801    [united states–mexico barrier, legs, arms, pap...
4802                                                   []
4803    [date, love at first sight, narration, investi...
4804                                                   []
4805            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [419]:
# helper function to fetch name
def fetch_character(obj):
    L = []
    i = 0
    for l in obj:
        if i != 3:
            L.append(l["name"])
            i += 1
        else:
            break
    return L

In [420]:
df["cast"]

0       [{'cast_id': 242, 'character': 'Jake Sully', '...
1       [{'cast_id': 4, 'character': 'Captain Jack Spa...
2       [{'cast_id': 1, 'character': 'James Bond', 'cr...
3       [{'cast_id': 2, 'character': 'Bruce Wayne / Ba...
4       [{'cast_id': 5, 'character': 'John Carter', 'c...
                              ...
4801    [{'cast_id': 1, 'character': 'El Mariachi', 'c...
4802    [{'cast_id': 1, 'character': 'Buzzy', 'credit_...
4803    [{'cast_id': 8, 'character': 'Oliver O’Toole',...
4804    [{'cast_id': 3, 'character': 'Sam', 'credit_id...
4805    [{'cast_id': 3, 'character': 'Herself', 'credi...
Name: cast, Length: 4806, dtype: object

In [421]:
df["cast"] = df["cast"].apply(fetch_character)

In [422]:
df["cast"][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [423]:
def fetch_producer(obj):
    L = []
    for item in obj:
        if item["job"] == "Producer":
            L.append(item["name"])
    
    return L

In [424]:
df["crew"] = df["crew"].apply(fetch_producer)

In [425]:
def extract_text(obj):
    L = list(map(lambda x : x, obj.split()))
    return L

In [426]:
df["overview"] = df["overview"].apply(extract_text)

In [427]:
def remove_space(obj):
    return list(map(lambda x: x.replace(" ", ""), obj))

In [428]:
df["cast"] = df["cast"].apply(remove_space)

In [429]:
df["crew"] = df["crew"].apply(remove_space)

In [430]:
df["genres"] = df["genres"].apply(remove_space)

In [431]:
df.head()

,id,genres,keywords,overview,title,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]","[JamesCameron, JonLandau]"
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[JerryBruckheimer, EricMcLeod, ChadOman, Peter..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]","[BarbaraBroccoli, MichaelG.Wilson]"
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]","[CharlesRoven, ChristopherNolan, EmmaThomas]"
4,49529,"[Action, Adventure, ScienceFiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]","[ColinWilson, JimMorris, LindseyCollins]"

In [432]:
new_df = df

In [433]:
new_df["tags"] = (new_df["genres"]+ new_df["cast"] + new_df["crew"] + new_df["overview"] + df["keywords"])

In [434]:
new_df = new_df.drop(columns=["genres", "keywords", "cast", "crew", "overview"])

In [435]:
new_df

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, S..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, JohnnyDepp, Orlan..."
2,206647,Spectre,"[Action, Adventure, Crime, DanielCraig, Christ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, ChristianBale..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, TaylorKits..."
...,...,...,...
4801,9367,El Mariachi,"[Action, Crime, Thriller, CarlosGallardo, Jaim..."
4802,72766,Newlyweds,"[Comedy, Romance, EdwardBurns, KerryBishé, Mar..."
4803,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, EricMabius, ..."
4804,126186,Shanghai Calling,"[DanielHenney, ElizaCoupe, BillPaxton, When, a..."
4805,25975,My Date with Drew,"[Documentary, DrewBarrymore, BrianHerzlinger, ..."

In [446]:
new_df["tags"] = new_df["tags"].apply(lambda x : " ".join(x))

In [449]:
new_df["tags"][0]

'Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron JonLandau In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d'

In [450]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english', max_features=5000)

In [453]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [463]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [471]:
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [481]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [482]:
new_df["tags"] = new_df["tags"].apply(stem)

In [486]:
new_df["tags"][0]

'action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron jonlandau in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d'

In [488]:
from sklearn.metrics.pairwise import cosine_similarity

In [490]:
similarity = cosine_similarity(vectors)

In [493]:
similarity[0]

array([1.        , 0.07290826, 0.03450328, ..., 0.0348684 , 0.01964944,
       0.        ])

In [497]:
def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [499]:
recommend("Batman Begins")

The Dark Knight
Batman
Batman
The Dark Knight Rises
Batman & Robin

In [501]:
import pickle

In [502]:
pickle.dump(new_df, open("movies.pkl", 'wb'))